### PR TITLE
change isntall_aur_package->install_aur_package

### PR DESCRIPTION
**Pull request by dpendolino**
Simple typo fix in the i3 install script.

### CODE REVIEW

**Comment by pauldotknopf** [comment]
I noticed you are getting busy with your fork.

How are things going? Any pain points that could suck less?

**Comment by dpendolino** [comment]
Yep I love the idea and I'm on paternity leave for a while so it's been fun to mess with.

First a few really nice things:

- Really ended up liking Polybar and Dotbot, so I'm folding them into my own configs
- `darch` does a lot but you have a good start on docs and the interface is laid out logically which I appreciate
- Thanks for being so responsive and engaged

Things to improve:
- Command flag inconsistencies (especially without completion). Basically `stage` vs `recipes`, it'd be nice to lose the `s` or have it everywhere
- Is there a verbose option, if not that would be nice. `sudo darch images pull ...` can take a while with no indication of progress
- I'm newish to Travis-CI but not new to CI in general. I'm hitting the 50 minute time limit for builds and have been thinking of ways to build all recipes better. I keep thinking of either finding a way to build independant images in parallel, maybe parsing `darch recipes tree` and building each leaf recipes and its dependant images in a separate VM or finding a way to determine if an image can be pulled rather than being rebuilt if no changes are made. 
- When building a recipes based on an external image, it would be nice if `darch` automatically pulled in the image 
- This might be more work than it's worth but my laptop is LUKS encrypted so I want to work out a way to detect that and generate an appropriate `grub` entry to decrypt it before booting

Sorry for the brain dump, cheers!

**Comment by pauldotknopf** [comment]
Thanks for the feedback!

> Command flag inconsistencies (especially without completion). Basically stage vs recipes, it'd be nice to lose the s or have it everywhere

[Agreed](https://github.com/godarch/darch/issues/13).

> Is there a verbose option, if not that would be nice. sudo darch images pull ... can take a while with no indication of progress

[Planned as well](https://github.com/godarch/darch/issues/9).

> I'm newish to Travis-CI but not new to CI in general. I'm hitting the 50 minute time limit for builds and have been thinking of ways to build all recipes better.

I have ran up against it too. Basically, anything with AUR sucks.

My thoughts are this. I will manually build on AUR packages myself, and create my own local repository (configured in ```/etc/pacman.conf```). I will store the database and files via GitHub releases (documented [here](https://fusion809.github.io/how-to-create-archlinux-repository/#toc12)). Then, my recipes will install AUR packages via pacman, and it will download the ```pkg.tar.gz``` directly from GitHub. No ```git clone``` from AUR, no package compression/etc. It will be as quick as installs from the main repos.

I was thinking about creating cli tool that wraps the building of the AUR packages and that managing of the GitHub release for you.

This will lose the "rolling" nature of the AUR, of course. So, it would be up to you to remember to periodically update the packages.

> thinking of either finding a way to build independant images in parallel

Me too. I created an [issue](https://github.com/godarch/darch/issues/15) to track it.

> When building a recipes based on an external image, it would be nice if darch automatically pulled in the image

[Agreed](https://github.com/godarch/darch/issues/14).

> my laptop is LUKS encrypted so I want to work out a way to detect that and generate an appropriate grub

Does it not do this currently? Do you have to always modify ```/etc/darch/grub.conf```? What changes do you have to make to it?

Thanks for the feedback!

I took an approach with this project that I typically do when I write software. That is to implement things straightforward (even if verbose) with little "black magic". As time evolves, I like to let things naturally evolve to be more performant and ergonomic. It will get there, eventually. When all the rough edges are smoothened, that is when I will make a ```1.0.0``` release.

**Comment by dpendolino** [comment]
> Thanks for the feedback!

Anytime!

> 
> Command flag inconsistencies (especially without completion). Basically stage vs recipes, it'd be nice to lose the s or have it everywhere
> 
> Agreed.
> 
> Is there a verbose option, if not that would be nice. sudo darch images pull ... can take a while with no indication of progress
> 
> Planned as well.
> 
> I'm newish to Travis-CI but not new to CI in general. I'm hitting the 50 minute time limit for builds and have been thinking of ways to build all recipes better.
> 
> I have ran up against it too. Basically, anything with AUR sucks.
> 
> My thoughts are this. I will manually build on AUR packages myself, and create my own local repository (configured in /etc/pacman.conf). I will store the database and files via GitHub releases (documented here). Then, my recipes will install AUR packages via pacman, and it will download the pkg.tar.gz directly from GitHub. No git clone from AUR, no package compression/etc. It will be as quick as installs from the main repos.

Ha, I was thinking of doing something similar for myself.

> 
> I was thinking about creating cli tool that wraps the building of the AUR packages and that managing of the GitHub release for you.
> 
> This will lose the "rolling" nature of the AUR, of course. So, it would be up to you to remember to periodically update the packages.

Neat!
> 
> thinking of either finding a way to build independant images in parallel
> 
> Me too. I created an issue to track it.
> 
> When building a recipes based on an external image, it would be nice if darch automatically pulled in the image
> 
> Agreed.
> 
> my laptop is LUKS encrypted so I want to work out a way to detect that and generate an appropriate grub
> 
> Does it not do this currently? Do you have to always modify /etc/darch/grub.conf? What changes do you have to make to it?

I haven't actually tried making it work, but yeah it looks like I would just need to edit the `grub` entry to work with my `cryptdevice`.

> 
> Thanks for the feedback!
> 
> I took an approach with this project that I typically do when I write software. That is to implement things straightforward (even if verbose) with little "black magic". As time evolves, I like to let things naturally evolve to be more performant and ergonomic. It will get there, eventually. When all the rough edges are smoothened, that is when I will make a 1.0.0 release.

Nice, glad to see you have a plan for moving forward =]

**Comment by pauldotknopf** [comment]
Hey, just letting you know.

I updated my recipes to use my precompiled images.

Items of interest:

https://github.com/pauldotknopf/darch-recipes/commit/9b706335368a19ef70c8e9f1e345ce0b74c68dec

https://github.com/pauldotknopf/github-release-sync

https://github.com/pauldotknopf/binary-repos/tree/arch-linux

My build time is back down to 16 minutes :)

**Comment by dpendolino** [comment]
> Hey, just letting you know.
> 
> I updated my recipes to use my precompiled images.

Awesome!

> 
> Items of interest:
> 
> 9b70633
> 
> https://github.com/pauldotknopf/github-release-sync
> 
> https://github.com/pauldotknopf/binary-repos/tree/arch-linux
> 
> My build time is back down to 16 minutes :)

That rocks, I can't wait to check this out. 

Oh so I tried getting an image to boot on my encrypted laptop but so far no dice. Here is the basic layout:

`sda1` - `/boot` - unencrypted ext2
`sda2` - LUKS volume -> LVM -> root + other partitions

Once I made `grub.cfg` happy and moved vmlinux and initrd into `/boot` it finally tried to boot but no luck decrypting `sda2`. What `mkinicpio` hooks are you using?

**Comment by pauldotknopf** [comment]
I am using [this](https://github.com/godarch/distributions/blob/master/arch/initcpio-hooks/darch-mkinitcpio.conf) mkinitcpio. See [this](https://github.com/godarch/distributions/blob/master/arch/Dockerfile#L8) too.

You can override this file in your recipes. Don't forgot to ```mkinitcpio -p linux``` in your recipes as well.

**Pull request merged**
